name: ipecstudents
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  provider: ^4.3.2
  flutter_bloc: ^4.0.1
  equatable: ^1.2.3
  dio: ^3.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: averta
      fonts:
        - asset: fonts/averta/Averta-Regular.ttf
        - asset: fonts/averta/Averta-Bold.ttf
          weight: 700