name: ipecstudentsapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.5.4+15

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_neumorphic: ^3.1.0
  adaptive_theme: ^2.2.0
  circular_profile_avatar: ^2.0.0
  cupertino_icons: ^1.0.3
  dio: ^4.0.0
  equatable: ^2.0.2
  # firebase_analytics: ^8.1.0
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  firebase_database: ^6.1.2
  firebase_messaging: ^10.0.0
  fl_chart: ^0.36.1
  flutter_bloc: ^4.0.1
  flutter_share: ^2.0.0
  flutter_svg: ^0.22.0
  flutter_webview_plugin: ^0.3.11
  html: ^0.15.0
  intl: ^0.17.0
  lottie: ^1.0.1
  mantras: ^0.0.3
  provider: ^4.0.5
  share: ^2.0.1
  shared_preferences: ^2.0.5
  shimmer: ^2.0.0
  syncfusion_flutter_pdfviewer: 
  url_launcher: ^6.0.4
  webview_flutter: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: null
  flutter_native_splash: null

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/anim/
    - assets/icons/

  fonts:
    - family: averta
      fonts:
        - asset: fonts/averta/Averta-Regular.ttf
        - asset: fonts/averta/Averta-Bold.ttf
          weight: 500

flutter_native_splash:
  image: assets/images/logo.png
  color: "#FFFFFF"
